version: '3'

services: 
  mariadb:
    image: mariadb:10.4.5
    container_name: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: passme
      MYSQL_DATABASE: fahrgemeinschaft
      MYSQL_USER: user
      MYSQL_PASSWORD: passme
    ports:
      - 3306:3306
    volumes:
      -  \project\db:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8000:80
    environment:
      MYSQL_ROOT_PASSWORD: passme
      
