version: '3'

services: 
  mariadb:
    image: mariadb:10.4.5
    container_name: mariadb
    environment: 
      MYSQL_ROOT_PASSWORD: passme
      MYSQL_DATABASE: fahrgemeinschaft
      MYSQL_USER: user
      MYSQL_PASSWORD: passme
    ports:
      - 3306:3306
    volumes:
      -  /db:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
      - 8000:80
    environment:
      MYSQL_ROOT_PASSWORD: passme
    
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - mariadb