default: &default
  adapter: mysql2
  encoding: utf8
  database: fahrgemeinschaft
  username: root
  password: passme
  host: localhost:8000
  port: 3306
development:
  <<: *default

test:
  <<: *default
  database: *default

production:
  <<: *default
